// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'kopo_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

KopoModel _$KopoModelFromJson(Map<String, dynamic> json) {
  return KopoModel(
    postcode: json['postcode'] as String,
    postcode1: json['postcode1'] as String,
    postcode2: json['postcode2'] as String,
    postcodeSeq: json['postcodeSeq'] as String,
    zonecode: json['zonecode'] as String,
    address: json['address'] as String,
    addressEnglish: json['addressEnglish'] as String,
    addressType: json['addressType'] as String,
    bcode: json['bcode'] as String,
    bname: json['bname'] as String,
    bname1: json['bname1'] as String,
    bname2: json['bname2'] as String,
    sido: json['sido'] as String,
    sigungu: json['sigungu'] as String,
    sigunguCode: json['sigunguCode'] as String,
    userLanguageType: json['userLanguageType'] as String,
    query: json['query'] as String,
    buildingName: json['buildingName'] as String,
    buildingCode: json['buildingCode'] as String,
    apartment: json['apartment'] as String,
    jibunAddress: json['jibunAddress'] as String,
    jibunAddressEnglish: json['jibunAddressEnglish'] as String,
    roadAddress: json['roadAddress'] as String,
    roadAddressEnglish: json['roadAddressEnglish'] as String,
    autoRoadAddress: json['autoRoadAddress'] as String,
    autoRoadAddressEnglish: json['autoRoadAddressEnglish'] as String,
    autoJibunAddress: json['autoJibunAddress'] as String,
    autoJibunAddressEnglish: json['autoJibunAddressEnglish'] as String,
    userSelectedType: json['userSelectedType'] as String,
    noSelected: json['noSelected'] as String,
    hname: json['hname'] as String,
    roadnameCode: json['roadnameCode'] as String,
    roadname: json['roadname'] as String,
  );
}

Map<String, dynamic> _$KopoModelToJson(KopoModel instance) => <String, dynamic>{
      'postcode': instance.postcode,
      'postcode1': instance.postcode1,
      'postcode2': instance.postcode2,
      'postcodeSeq': instance.postcodeSeq,
      'zonecode': instance.zonecode,
      'address': instance.address,
      'addressEnglish': instance.addressEnglish,
      'addressType': instance.addressType,
      'bcode': instance.bcode,
      'bname': instance.bname,
      'bname1': instance.bname1,
      'bname2': instance.bname2,
      'sido': instance.sido,
      'sigungu': instance.sigungu,
      'sigunguCode': instance.sigunguCode,
      'userLanguageType': instance.userLanguageType,
      'query': instance.query,
      'buildingName': instance.buildingName,
      'buildingCode': instance.buildingCode,
      'apartment': instance.apartment,
      'jibunAddress': instance.jibunAddress,
      'jibunAddressEnglish': instance.jibunAddressEnglish,
      'roadAddress': instance.roadAddress,
      'roadAddressEnglish': instance.roadAddressEnglish,
      'autoRoadAddress': instance.autoRoadAddress,
      'autoRoadAddressEnglish': instance.autoRoadAddressEnglish,
      'autoJibunAddress': instance.autoJibunAddress,
      'autoJibunAddressEnglish': instance.autoJibunAddressEnglish,
      'userSelectedType': instance.userSelectedType,
      'noSelected': instance.noSelected,
      'hname': instance.hname,
      'roadnameCode': instance.roadnameCode,
      'roadname': instance.roadname,
    };
